Error: Refer non-zero line numbers only
Some of the tools like cppcheck and splint report line number along
with text error. However, valgrind does not report line number on each
error. Therefore, modify the Error class to use line number in string
representation only if it has been reported by the tool.

Signed-off-by: Prasad Joshi <prasadjoshi124@gmail.com>